common: &common
  pool: 5
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432

development:
  <<: *common
  database: rdhedusrv
  username: postgres
  password:

production:
  <<: *common
  database: rdhedusrv_production
  username: postgres
  password:

#test:
#  <<: *common
#  database: rdhedusrv_test
#  username: postgres
#  password:


